feat: add nav-bar
dscnitrourkela/project-oregano pull request #163
Opened 2022-10-18 17:52 UTC by Shurtu-gal

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [x] Make sure you are making a pull request against the **default branch** (left side). Also you should start *your branch* off *default branch*.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Description
Please describe your pull request.

❤️Thank you!

### Post merge checklist
- [x] Follow steps from the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
- [x] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2022-10-19 03:11 UTC, Shurtu-gal commented
@riteshsp2000 @ORKO06 @ratnakar5938 
Can you kindly review the changes?

Thank you

2022-11-06 12:05 UTC, ratnakar5938 requested changes

2022-11-06 12:10 UTC, Shurtu-gal commented on src/components/content/content.js
> +};
Sure

2022-11-06 12:23 UTC, ratnakar5938 approved these changes

2022-11-06 16:20 UTC, ratnakar5938 commented
@Shurtu-gal change the file structure to that of 3.0

2022-11-06 17:47 UTC, ratnakar5938 commented
@Shurtu-gal Why are there 2 types of hamburgermenu in the design 
![Screenshot (292)](https://user-images.githubusercontent.com/80893583/200186495-cee06121-4fe2-4349-88b3-632ea5d9b553.png)
![Screenshot (293)](https://user-images.githubusercontent.com/80893583/200186500-09ed9fef-2f8d-41ad-9c46-406b17df117f.png)

2022-11-10 08:40 UTC, ratnakar5938 commented
LGTM 🚀

2022-11-11 10:17 UTC, padmajabhol approved these changes

2022-11-11 10:17 UTC, merged