hero section modified
dscnitrourkela/project-oregano pull request #239
Opened 2023-10-14 12:56 UTC by ishita-1305

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start *your branch* off *default branch*.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Description
Please describe your pull request.

❤️Thank you!

### Post merge checklist
- [ ] Follow steps from the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2023-10-24 12:24 UTC, Lucif3r-in commented
Make the requested changes @ishita-1305

2023-10-25 04:51 UTC, Lucif3r-in commented
@ishita-1305 `5.0` should be right aligned and the text should be justified. The `Hack` also gets smaller than `NITR` on smaller screens

2023-10-25 11:43 UTC, SirSimon162 commented
@ishita-1305 
- Fix the typography in the hero section for mobile view.
- Fix the padding around 'Hack' image in mobile view.
- Fix the mobile view as per the design.
- Focus on alignment.

2023-10-25 12:13 UTC, ishita-1305 reviewed
-fixed alignment in mobile screen
-fixed the padding around 'Hack' image in mobile view.
-fixed the mobile view as per the design.
-removed the buttons

2023-10-25 16:11 UTC, Lucif3r-in commented
Keep the width of divs containing HackNITR, 5.0 and the text beneath same

2023-10-25 16:12 UTC, Lucif3r-in commented
Add `cursor:pointer` to buttons and make the `flex-directiion:column` for smaller screens

2023-10-27 16:51 UTC, Lucif3r-in commented
@ishita-1305 Make changes according to figma file.

2023-11-02 04:18 UTC, Lucif3r-in commented
Resolve merge conflicts @ishita-1305

2023-11-02 16:12 UTC, anmol5936 commented on src/components/HeroSection/styles.jsx
> +export const heroBelow = styled.div`
remove heroBelow from here.

2023-11-02 16:13 UTC, anmol5936 commented on src/components/HeroSection/HeroSection.jsx
> +          <heroBelow className='mx-8 md:max-w-xl lg:max-w-3xl'>
no need to use heroBelow tag instead use another name

2023-11-02 18:41 UTC, Lucif3r-in requested changes

2023-11-02 18:41 UTC, Lucif3r-in commented on src/components/HeroSection/HeroSection.jsx
> +            </HeroHeading>
Why do we need two wrappers wrapping the same component?

2023-11-02 18:41 UTC, Lucif3r-in commented on src/components/HeroSection/styles.jsx
> +
run prettier once in the file

2023-11-02 18:41 UTC, Lucif3r-in commented on src/components/shared/DevfolioButton.jsx
> +/* eslint-disable max-len */
Remove unwanted comments

2023-11-06 18:22 UTC, Lucif3r-in requested changes

2023-11-06 18:22 UTC, Lucif3r-in commented on src/components/HeroSection/styles.jsx
> +
Run prettier once in all these files please

2023-11-08 17:48 UTC, Lucif3r-in commented
LGTM🚀

2023-11-08 17:51 UTC, Lucif3r-in requested changes

2023-11-08 17:51 UTC, Lucif3r-in commented on src/pages/index.js
> +
Remove this change

2023-11-08 17:51 UTC, Lucif3r-in commented on src/pages/index.js
> +
Extra line

2023-11-08 17:51 UTC, Lucif3r-in commented on src/styles/global.css
> +
Extra line

2023-11-08 17:51 UTC, Lucif3r-in commented on src/components/shared/DiscordButton.jsx
> +
Remove extra spaces run prettier

2023-11-08 17:51 UTC, Lucif3r-in commented on src/components/shared/DevfolioButton.jsx
> +
Run prettier in all the files once

2023-11-08 17:51 UTC, Lucif3r-in commented on src/components/shared/DevfolioBtn.css
> +
Remove extra space

2023-11-08 17:51 UTC, Lucif3r-in commented on src/components/shared/DevfolioBtn.css
> +
Here too

2023-11-09 08:17 UTC, Lucif3r-in commented
LGTM🚀🚀

2023-11-09 08:17 UTC, merged