initial commit
dscnitrourkela/project-oregano pull request #248
Opened 2023-10-19 13:47 UTC by aryab2003

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start *your branch* off *default branch*.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Description
Please describe your pull request.

❤️Thank you!

### Post merge checklist
- [ ] Follow steps from the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2023-10-26 19:30 UTC, Lucif3r-in commented
@aryab2003 You have not imported your component in playground.js.
There are some changes in `yarn.lock` please remove them.

2023-10-27 05:50 UTC, aryab2003 commented
> @aryab2003 You have not imported your component in playground.js. There are some changes in `yarn.lock` please remove them.
Imported Prizes in playground but then the  deploy preview failed.

2023-11-02 18:34 UTC, Lucif3r-in requested changes

2023-11-02 18:34 UTC, Lucif3r-in commented on src/components/Prizes/Prizes.jsx
> +const imageUrls = ["https://res.cloudinary.com/dkpdi1wek/image/upload/v1698839425/gold_zvb6fu.png", "https://res.cloudinary.com/dkpdi1wek/image/upload/v1698839425/silver_ramqno.png", "https://res.clo
Move these to `config/content/Prizes.js`

2023-11-02 18:34 UTC, Lucif3r-in commented on src/components/Prizes/Prizes.jsx
> +const prizeShadowColors = ['#43F4AA', '#02AECC', '#7D34CC'];
Import the colors from `global.css`

2023-11-07 17:36 UTC, RickDeb2004 commented
@aryab2003 push the recent changes

2023-11-08 16:49 UTC, SirSimon162 commented
@aryab2003 
- Use image only for trophy image
- Make a component for 'Explore' text
- Make the UI like the design provided
- Fix the height of card when expanded in mobile view

2023-11-09 18:00 UTC, aryab2003 commented
@SirSimon162 help in box height for mobile design

2023-11-09 18:01 UTC, aryab2003 commented
@SirSimon162 help me in making a separate winner component

2023-11-11 11:58 UTC, SirSimon162 commented on src/components/Prizes/styles.js
> +  margin-top: 20px;
Font size should be 40px with line height 40px in PrizesTitle

2023-11-11 12:00 UTC, SirSimon162 commented on src/components/Prizes/styles.js
> +  font-size: 28px;
Font size should be 40px and line height 40px according to the design.

2023-11-11 12:01 UTC, SirSimon162 commented on src/components/Prizes/styles.js
> +  font-size: 16px;
font size should be 18px and line height 24px.

2023-11-11 12:05 UTC, SirSimon162 commented on src/components/Prizes/styles.js
> +  margin-top: 16px;
change margin top to 32px for larger screens.

2023-11-11 18:53 UTC, SirSimon162 commented
Fix the card size more mobile view
![image](https://github.com/dscnitrourkela/project-oregano/assets/103681122/1113d839-6402-4da8-aea9-ee739f6c60da)

2023-11-11 18:53 UTC, SirSimon162 commented
Make it center aligned
![image](https://github.com/dscnitrourkela/project-oregano/assets/103681122/1896d1cf-2348-486d-a08e-77f70d762bbf)

2023-11-11 19:19 UTC, aryab2003 commented
> Fix the card size more mobile view 

This issue is not getting fixed at whatever px i am setting..need help

2023-11-11 19:23 UTC, SirSimon162 commented on src/components/Prizes/styles.js
> +  line-height: 28px;
You have used line height twice. Remove the line with line height 28px.

2023-11-11 19:26 UTC, SirSimon162 commented on src/components/Prizes/styles.js
> +  margin-top: 32px;
give row-gap: 5px;

2023-11-11 19:31 UTC, SirSimon162 commented
@aryab2003 For making a separate winner component. Export only trophy image from Figma and put that in a div along with another div containing the Winner text and the icon. Make all of them center aligned.

2023-11-13 19:48 UTC, merged