feat:Add Aboutus
dscnitrourkela/project-oregano pull request #255
Opened 2023-10-21 20:15 UTC by babitarit

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start *your branch* off *default branch*.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Description
Please describe your pull request.

❤️Thank you!

### Post merge checklist
- [ ] Follow steps from the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2023-10-25 11:12 UTC, SirSimon162 commented
@babitarit 
- Slower down the carousel.
- Why do you have a black background in About us? Remove that.
- Change the size of images as per design. Mobile view isn't as per the design.

2023-10-26 17:05 UTC, Lucif3r-in commented
The component is according to design just place the arrows for smaller screens and it will be ready

2023-10-26 19:53 UTC, SirSimon162 commented
@babitarit 

- Make the carousel center aligned 
![image](https://github.com/dscnitrourkela/project-oregano/assets/103681122/1a2b14a1-124d-460c-bd09-f2f84201dd5e)

- Fix this horizontal scroll bar
![image](https://github.com/dscnitrourkela/project-oregano/assets/103681122/64bd798c-5f4e-45f5-8723-5fbeced55ddc)

2023-10-27 15:46 UTC, ORKO06 commented on src/components/About/Slid.jsx
> +import { useState } from 'react';
Why is useState importing in seperate line

2023-10-27 15:53 UTC, ORKO06 requested changes

2023-10-27 15:53 UTC, ORKO06 commented on src/components/About/Slid.jsx
> +import { useState } from 'react';
Why is useState is imported in seperate line?

2023-10-27 15:53 UTC, ORKO06 commented on src/components/About/Slid.jsx
> +// }
Remove the unnecessary Comments

2023-10-27 15:53 UTC, ORKO06 commented on src/components/About/Slid.jsx
> +    // dots: true,
Remove the comments

2023-10-27 15:53 UTC, ORKO06 commented on src/components/About/Slid.jsx
> +    // ),
Remove the comments

2023-10-27 15:53 UTC, ORKO06 commented on src/components/About/Slid.jsx
> +
Unnecessary Spacing

2023-10-27 15:53 UTC, ORKO06 commented on src/components/About/Slid.jsx
> +function slid() {
Use a better naming convention

2023-10-27 15:53 UTC, ORKO06 commented on src/components/About/App.css
> +
Unnecessary spacing

2023-10-27 15:53 UTC, ORKO06 commented on src/components/About/About.jsx
Why are we making new text components for header and body. Why are we not using components from design system

@SirSimon162 @Lucif3r-in @babitarit

2023-10-27 16:28 UTC, Lucif3r-in requested changes

2023-10-27 16:28 UTC, Lucif3r-in commented on src/components/About/About.jsx
> +`;
Use typography, do not create your own text components

2023-10-27 16:28 UTC, Lucif3r-in commented on src/components/About/About.jsx
> +      </Body2>
Relocate these text to `config/content/AboutUs.js`

2023-10-27 16:28 UTC, Lucif3r-in commented on src/components/About/App.css
> +
Do not use css file, we are already using styled-components for this.

2023-10-27 16:28 UTC, Lucif3r-in commented on src/components/About/Slid.jsx
> +import img4 from '../images/img1.png';
Use cloudinary links instead of local assets.

2023-10-27 17:12 UTC, Shurtu-gal commented
@babitarit There are some merge conflicts

2023-11-02 18:26 UTC, Lucif3r-in requested changes

2023-11-02 18:26 UTC, Lucif3r-in commented on src/components/images/img1.png
Remove these images and use cloudinary links.

2023-11-02 18:26 UTC, Lucif3r-in commented on src/components/About/App.css
Use styled-components in `styles.js`, do not use css file.

2023-11-02 18:26 UTC, Lucif3r-in commented on src/components/About/About.jsx
> +`;
Create a new file `styles.js` and move these there.

2023-11-02 18:26 UTC, Lucif3r-in commented on src/components/About/Carousel.jsx
> +    </div>
use styled-components rather than using classes for css

2023-11-02 18:26 UTC, Lucif3r-in commented on src/components/shared/Typography/Body2.jsx
> +
remove this extra space

2023-11-08 14:40 UTC, closed without merging