feat: add aboutus section
dscnitrourkela/project-oregano pull request #263
Opened 2023-11-07 14:08 UTC by babitarit

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start *your branch* off *default branch*.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Description
Please describe your pull request.

❤️Thank you!

### Post merge checklist
- [ ] Follow steps from the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2023-11-10 06:20 UTC, RickDeb2004 commented
![image](https://github.com/dscnitrourkela/project-oregano/assets/113274631/add69f9c-b272-4eb4-91d1-306271bfb95d)
check this once @babitarit

2023-11-11 12:14 UTC, SirSimon162 commented on src/components/AboutUs/About.jsx
> +        <Heading1>About Us</Heading1>
Create a styled component for this. Add font weight of 700.

2023-11-11 12:15 UTC, SirSimon162 commented on src/components/AboutUs/styles.js
> +    width: 80%;
add font size 16px and line height 24px.

2023-11-11 12:21 UTC, SirSimon162 commented on src/components/AboutUs/Carousel.jsx
> +    <div className='container'>
don't use classNames. Replace all the classNames with styled components.

2023-11-13 15:22 UTC, Lucif3r-in requested changes

2023-11-13 15:22 UTC, Lucif3r-in commented on src/components/AboutUs/Carousel.jsx
> +function Carousel() {
Rename this as `AboutCarousel`

2023-11-13 15:22 UTC, Lucif3r-in commented
@babitarit Resolve merge conflicts

2023-11-13 18:54 UTC, merged