feat : Prevstats section added
dscnitrourkela/project-oregano pull request #275
Opened 2023-12-06 07:19 UTC by anmol5936

2023-12-06 10:49 UTC, Lucif3r-in commented
![image](https://github.com/dscnitrourkela/project-oregano/assets/85403534/9f2c91b3-08c7-41fd-aa0f-fce4a987d16e)
Not responsive at all @anmol5936 . Please complete by tonight

2023-12-06 11:23 UTC, Lucif3r-in commented
Also the length of individual stats should be according to design

2023-12-08 06:54 UTC, SirSimon162 commented
Change the website title to HackNITR 5.0 @anmol5936

2023-12-08 06:57 UTC, SirSimon162 commented
![Screenshot (3)](https://github.com/dscnitrourkela/project-oregano/assets/103681122/6fa4fcb0-11fc-4880-a2e0-8616369546f6)
Fix this overflow @anmol5936

2023-12-08 07:00 UTC, SirSimon162 commented
The cards should be left aligned and should move in one direction like it is in the design. Follow the design properly and keep animation exactly the same @anmol5936 
https://www.figma.com/proto/xwjkgivbXD5BKUwJwT4JIy/HN-5.0-website-real?type=design&node-id=255-1275&t=jpQdYxTCNbIGDKZc-0&scaling=min-zoom&page-id=55%3A710&starting-point-node-id=255%3A1275

2023-12-08 07:56 UTC, Shurtu-gal reviewed
At last, it should look like:- 
![image,](https://github.com/dscnitrourkela/project-oregano/assets/100484401/66edd3df-cc4d-46d5-8f48-e8126ac58c29)

2023-12-08 07:56 UTC, Shurtu-gal commented on src/components/PrevStats/PreviousStats.jsx
> +    const handleResize = () => {
Try to do this with media queries.

2023-12-08 07:56 UTC, Shurtu-gal commented on src/components/PrevStats/PreviousStats.jsx
> +    setIsHovered((prev) => prev.map((_, i) => i === index));
This can also be done with CSS. The problem with onHover is it results in janky animation when state changes during animation itself.

2023-12-08 07:56 UTC, Shurtu-gal commented on src/components/PrevStats/PreviousStats.jsx
> +                  <MobileSubContent>Registration</MobileSubContent>
Could use map over Object.keys and headers can be put into content too.

2023-12-08 07:56 UTC, Shurtu-gal commented on src/components/PrevStats/PreviousStats.jsx
> +                  </BoxSubContent>
Same here

2023-12-08 07:56 UTC, Shurtu-gal commented on src/components/PrevStats/PreviousStats.jsx
> +          <SectionCards expanded={isHovered} value='600px'>
What does value means here?

2023-12-08 07:56 UTC, Shurtu-gal commented on src/components/PrevStats/styles.js
> +  padding-right: 34vw;
Crop the XORI image and remove these paddings.

2023-12-08 07:56 UTC, Shurtu-gal commented on src/components/PrevStats/styles.js
> +  padding-left: 18rem;
This also.

2023-12-08 07:56 UTC, Shurtu-gal commented on src/components/PrevStats/styles.js
> +  justify-content: center;
Not needed as it should be left aligned as it grows.

2023-12-08 07:56 UTC, Shurtu-gal commented on src/components/PrevStats/styles.js
> +  display: flex;
Can use grid as we don't want layout to shift.

2023-12-09 11:37 UTC, Lucif3r-in commented
![image](https://github.com/dscnitrourkela/project-oregano/assets/85403534/285e8f63-72f0-4a8f-903b-7addf42adc51)
Horizontally center the component.

2023-12-10 11:23 UTC, Lucif3r-in requested changes

2023-12-10 11:23 UTC, Lucif3r-in commented on src/pages/index.js
> +          <PreviousStats />
move previous stats after about us section

2023-12-10 13:27 UTC, Lucif3r-in requested changes

2023-12-10 13:27 UTC, Lucif3r-in commented on config/content/navbar.js
>      { id: 'Home', name: 'Home', link: '/#Home' },
change `link: '/'`

2023-12-10 14:11 UTC, merged