Added New Timeline
dscnitrourkela/project-oregano pull request #291
Opened 2024-01-19 13:11 UTC by Seventy7dot2

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start *your branch* off *default branch*.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Description
Please describe your pull request.

❤️Thank you!

### Post merge checklist
- [ ] Follow steps from the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2024-01-21 05:03 UTC, ashutosh-rath02 commented
Attach a screen recoding of the component for multiple screens @Seventy7dot2 .

2024-01-21 05:05 UTC, ashutosh-rath02 requested changes

2024-01-21 05:05 UTC, ashutosh-rath02 commented on config/content/Timelinecontent.js
Remove the previous timeline component and change the file name

2024-01-22 17:01 UTC, Seventy7dot2 commented
> Attach a screen recoding of the component for multiple screens @Seventy7dot2 .


Uploading Screen Recording 2024-01-22 at 10.29.44 PM.mov…

2024-01-22 17:04 UTC, Seventy7dot2 commented
> Attach a screen recoding of the component for multiple screens @Seventy7dot2 .


https://github.com/dscnitrourkela/project-oregano/assets/114677481/d8c0c07b-7f1e-4855-96b5-6fcbe1bd7b6f

2024-01-23 08:40 UTC, ashutosh-rath02 commented
@Seventy7dot2 The animation is not smooth please look into it

2024-01-23 09:34 UTC, Seventy7dot2 commented
> @Seventy7dot2 The animation is not smooth please look into it

It is smooth. The problem in the video is cause of the responsive interface of chrome

2024-01-31 04:31 UTC, ashutosh-rath02 commented
@Shurtu-gal Can you provide the link to this preview?

2024-01-31 06:16 UTC, Shurtu-gal commented
This has not been deployed.

2024-01-31 06:20 UTC, Shurtu-gal requested changes
Change base branch to `hacknitr5.0`.

2024-01-31 08:12 UTC, SirSimon162 commented
@Seventy7dot2 resolve conflicts

2024-01-31 14:30 UTC, Seventy7dot2 commented
> @Seventy7dot2 resolve conflicts

Done!👍

2024-01-31 16:24 UTC, closed without merging

2024-01-31 16:24 UTC, Shurtu-gal commented
@Seventy7dot2 open a new PR with branch `hacknitr5.0`.