feat: add sponsor section
dscnitrourkela/project-oregano pull request #37
Opened 2021-07-18 10:49 UTC by ratnakar5938

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [x] Make sure you are making a pull request against the **default branch** (left side). Also you should start *your branch* off *default branch*.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [x] I have added necessary documentation (if appropriate)

### Description
Please describe your pull request.

❤️Thank you!

### Post merge checklist
- [ ] Follow steps from the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2021-07-19 04:13 UTC, abhibhaw requested changes
@CIPHERTron Reloading the page on a slow connection is distorting the design paint. Try to find a fix

2021-07-19 04:13 UTC, abhibhaw commented on src/components/SponsorsSection/Sponsor.jsx
> +          <SponsorIcon pic='sponsor' />
Replace these repetitive components with iterating over a list of sponsor pictures

2021-07-19 06:38 UTC, CIPHERTron commented
> @CIPHERTron Reloading the page on a slow connection is distorting the design paint. Try to find a fix

@abhibhaw I think this happens because Nextjs fetches the styles after rendering the page

https://dev.to/rsanchezp/next-js-and-styled-components-style-loading-issue-3i68
I'm not sure but this might be the solution to our problem. Let me look into it!

2021-07-19 08:16 UTC, abhibhaw commented
This should work or maybe we need a preloader?

> > @CIPHERTron Reloading the page on a slow connection is distorting the design paint. Try to find a fix
> 
> @abhibhaw I think this happens because Nextjs fetches the styles after rendering the page
> 
> https://dev.to/rsanchezp/next-js-and-styled-components-style-loading-issue-3i68
> I'm not sure but this might be the solution to our problem. Let me look into it!

2021-07-20 17:08 UTC, CIPHERTron commented
> This should work or maybe we need a preloader?
> 
> > > @CIPHERTron Reloading the page on a slow connection is distorting the design paint. Try to find a fix
> > 
> > 
> > @abhibhaw I think this happens because Nextjs fetches the styles after rendering the page
> > https://dev.to/rsanchezp/next-js-and-styled-components-style-loading-issue-3i68
> > I'm not sure but this might be the solution to our problem. Let me look into it!

We are going to need a preloader :')

2021-07-21 17:04 UTC, riteshsp2000 commented
> > This should work or maybe we need a preloader?
> > > > @CIPHERTron Reloading the page on a slow connection is distorting the design paint. Try to find a fix
> > > 
> > > 
> > > @abhibhaw I think this happens because Nextjs fetches the styles after rendering the page
> > > https://dev.to/rsanchezp/next-js-and-styled-components-style-loading-issue-3i68
> > > I'm not sure but this might be the solution to our problem. Let me look into it!
> 
> We are going to need a preloader :')

Technically speaking a preloader is nothing but again css. You will be using css preloader waiting for css to load. Also I'm using a similar setup of gatsby and styled components on my website, there isn't this issue, might be something with tailwind. Need to check that again, otherwise a preloader might not help

2021-07-21 17:06 UTC, CIPHERTron commented
> > > This should work or maybe we need a preloader?
> > > > > @CIPHERTron Reloading the page on a slow connection is distorting the design paint. Try to find a fix
> > > > 
> > > > 
> > > > @abhibhaw I think this happens because Nextjs fetches the styles after rendering the page
> > > > https://dev.to/rsanchezp/next-js-and-styled-components-style-loading-issue-3i68
> > > > I'm not sure but this might be the solution to our problem. Let me look into it!
> > 
> > We are going to need a preloader :')
> 
> Technically speaking a preloader is nothing but again css. You will be using css preloader waiting for css to load. Also I'm using a similar setup of gatsby and styled components on my website, there isn't this issue, might be something with tailwind. Need to check that again, otherwise a preloader might not help
> 

🥲🥲🥲

2021-07-22 07:23 UTC, CIPHERTron commented
Heyy @ratnakar5938 , is the mapping done?

2021-07-22 07:39 UTC, ratnakar5938 commented
> Heyy @ratnakar5938 , is the mapping done?

Yeah it is done

2021-07-22 07:39 UTC, ratnakar5938 commented
Should I commit it??

2021-07-22 08:26 UTC, CIPHERTron commented
> Should I commit it??

yeah sure!

2021-07-22 11:33 UTC, CIPHERTron commented
Also, @ratnakar5938, the grid view is not applied. Kindly check that once.
Logos are overlapping in `md`, `sm` & `xs` views. 
Fix that and commit the changes again!

2021-07-22 12:37 UTC, ratnakar5938 commented
> Also, @ratnakar5938, the grid view is not applied. Kindly check that once.
> Logos are overlapping in `md`, `sm` & `xs` views.
> Fix that and commit the changes again!

Please check now bhaiya i have fixed that issue

2021-07-22 17:00 UTC, riteshsp2000 commented
@ratnakar5938 Looks all good, one small change, instead of 3 in a row in mobile view, can you make it 2 in a row for mobile view?

2021-07-24 06:33 UTC, CIPHERTron commented
Good work @ratnakar5938 
One last thing. Pull upstream main to this i.e `ratnakar-2` branch of yours locally, resolve the conflicts and commit the changes.

2021-07-24 08:05 UTC, riteshsp2000 approved these changes

2021-07-24 08:05 UTC, abhibhaw approved these changes
Good job @ratnakar5938

2021-07-24 08:05 UTC, CIPHERTron approved these changes

2021-07-24 08:10 UTC, merged

2021-07-24 08:28 UTC, abhibhaw commented
@riteshsp2000 squash krna tha 😆

2021-07-24 08:31 UTC, riteshsp2000 commented
Naa bhai squash kyun? Bichare ka pura commits chala jata 🥲

2021-07-24 08:44 UTC, CIPHERTron commented
> Naa bhai squash kyun? Bichare ka pura commits chala jata 🥲

So kind XD

2021-07-24 08:45 UTC, CIPHERTron commented
@all-contributors add @ratnakar5938 for Code

2021-07-24 08:49 UTC, abhibhaw commented
> Naa bhai squash kyun? Bichare ka pura commits chala jata 🥲

ahh the squash pain 🗡️