feat: Add "Be A Hacker" Section
dscnitrourkela/project-oregano pull request #41
Opened 2021-07-20 11:38 UTC by sambit-sankalp

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [x] Make sure you are making a pull request against the **default branch** (left side). Also you should start *your branch* off *default branch*.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [x] I have added necessary documentation (if appropriate)

### Description
Please describe your pull request.

❤️Thank you!

### Post merge checklist
- [x] Follow steps from the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
- [x] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2021-07-21 16:59 UTC, riteshsp2000 commented
Hey @sambit-sankalp, a few changes before reviewing the PR.

1. Send all the images used in this PR to @CIPHERTron and get cloudinary links for those.
2. The register button looks cool. A few changes which I feel would be nice are, instead of making the entire button white, just make the border white color with text white. When howered on the button, you can fill it with white color and make the text black instead the current black background on shower.
3. The cards are not fully responsive and are overlapping at a few places. Also the width of the card is not adjusting as per the screen. Have a look at [project-guava-web](https://github.com/dscnitrourkela/project-guava-web), I have a similar setup which adjusts the card width.

Rest all looks good, we'll go through the code and suggest any changes if necessary

2021-07-22 09:59 UTC, riteshsp2000 requested changes

2021-07-22 09:59 UTC, riteshsp2000 commented on src/components/HackerSection/BeAHacker.jsx
> +            <HackerCard />
Indentation issue. Fix it

2021-07-22 09:59 UTC, riteshsp2000 commented on src/components/HackerSection/BeAHacker.jsx
> +
We use 2 space indentation. All of your code is with 4 space indentation.

2021-07-24 10:40 UTC, CIPHERTron approved these changes

2021-07-24 10:41 UTC, riteshsp2000 approved these changes

2021-07-24 10:41 UTC, abhibhaw approved these changes

2021-07-24 10:41 UTC, merged

2021-07-25 04:09 UTC, riteshsp2000 commented
@all-contributors add @sambit-sankalp for Code

2021-07-25 05:53 UTC, CIPHERTron commented
@all-contributors add @sambit-sankalp for Code