Footer create
dscnitrourkela/project-oregano pull request #51
Opened 2021-07-24 18:32 UTC by ORKO06

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start *your branch* off *default branch*.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Description
Please describe your pull request.

❤️Thank you!

### Post merge checklist
- [ ] Follow steps from the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2021-07-25 08:05 UTC, CIPHERTron requested changes

2021-07-25 08:05 UTC, CIPHERTron commented on src/components/marginals/Footer/Footer.jsx
> +        <SectionCard2>
@ORKO06 tell me one thing. Both the cards in the footer are of same structure and style. So, what's the need of making two card components i.e `SectionCard1` and `SectionCard2`?

Don't you think it's redundant?

2021-07-25 08:05 UTC, CIPHERTron commented on src/components/marginals/Footer/Footer.styles.js
> +  col-start-2
Also, you haven't used grid here. It's more like you've hard-coded the dimensions of the card component by specifying `col-spam-4` and `row-span-2`

Where as, what you should have done instead is you could've used a Wrapper with display grid i.e:
`grid grid-cols-3` and then, inside the Wrapper, you could've mapped to the card contents returning the Card component.

2021-07-28 04:06 UTC, riteshsp2000 commented
Hey @ORKO06. There are quite a few changes required.

1. Why are you using section container. Section container takes up the full height of the screen which we don't want for containers.
2. Why are you placing the footer inside a container? It should expand throughout the screen (in terms of width). What is to be done here is, the light grey background part should extend throughout the screen and the contents of the footer should be within the container. So remove the footer from the container (in pages/index.js) and use container in the footer component.
3. The design of the footer is of 3 column layout. You are using a 2 column thinge. 
4. The colour of the icons is greyish (secondary colour), you are using white.
5. The 2 cards are the exact same component, so why 2 different components?

2021-07-29 19:15 UTC, riteshsp2000 approved these changes

2021-07-30 05:50 UTC, CIPHERTron approved these changes

2021-07-30 09:36 UTC, merged