feat: Add Discord Icon
dscnitrourkela/project-oregano pull request #98
Opened 2021-09-12 15:35 UTC by CIPHERTron

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [X] Make sure you are making a pull request against the **default branch** (left side). Also you should start *your branch* off *default branch*.
- [X] Check the commit's or even all commits' message styles matches our requested structure.
- [X] Check your code additions will fail neither code linting checks nor unit test.
- [X] I have added necessary documentation (if appropriate)

### Description
Please describe your pull request.

❤️Thank you!

### Post merge checklist
- [ ] Follow steps from the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2021-09-12 17:32 UTC, abhibhaw requested changes

2021-09-12 17:32 UTC, abhibhaw commented on config/content/Hero.js
> +      link: 'https://discord.com/invite/SGzuZyp9nS',
Invalid Invite put hacknitr.tech/discord

2021-09-12 17:32 UTC, abhibhaw commented on config/content/Sponsors.js
> +      link: 'https://www.leadlearners.ca/',
Leading learner 2 baar ig??

2021-09-12 17:50 UTC, abhibhaw approved these changes
lgtm!!

2021-09-13 05:44 UTC, riteshsp2000 approved these changes

2021-09-13 05:45 UTC, merged